#云编译公用核心
name: OWRT-CORE-LITE

on:
  #公用核心标识
  workflow_call:
    inputs:
      OWRT_TARGET:
        required: true
        type: string
      OWRT_THEME:
        required: true
        type: string
      OWRT_NAME:
        required: true
        type: string
      OWRT_URL:
        required: true
        type: string
      OWRT_PW:
        required: true
        type: string
      OWRT_IP:
        required: true
        type: string
      OWRT_CFG:
        required: true
        type: string
      OWRT_BRANCH:
        required: true
        type: string
      OWRT_TYPE:
        required: true
        type: string
      OWRT_LINUX:
        required: true
        type: string
      OWRT_FILES:
        required: true
        type: string
      DIY_P1_SH:
        required: true
        type: string
      DIY_P2_SH:
        required: true
        type: string
      DIY_P3_SH:
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  OWRT_TARGET: ${{inputs.OWRT_TARGET}}
  OWRT_THEME: ${{inputs.OWRT_THEME}}
  OWRT_NAME: ${{inputs.OWRT_NAME}}
  OWRT_URL: ${{inputs.OWRT_URL}}
  OWRT_PW: ${{inputs.OWRT_PW}}
  OWRT_IP: ${{inputs.OWRT_IP}}
  OWRT_CFG: ${{inputs.OWRT_CFG}}
  OWRT_BRANCH: ${{inputs.OWRT_BRANCH}}
  OWRT_TYPE: ${{inputs.OWRT_TYPE}}
  OWRT_LINUX: ${{inputs.OWRT_LINUX}}
  OWRT_FILES: ${{inputs.OWRT_FILES}}
  DIY_P1_SH: ${{inputs.DIY_P1_SH}}
  DIY_P2_SH: ${{inputs.DIY_P2_SH}}
  DIY_P3_SH: ${{inputs.DIY_P3_SH}}
  TZ: Asia/Shanghai
  #USE_CACHEWRTBUILD: true
  
jobs:
  owrt_core_lite:
    runs-on: ubuntu-latest
    steps:
    
      - name: 清理服务器空间(Ubuntu)
        uses: rmoyulong/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
        
      - name: 项目检查
        uses: actions/checkout@main

      - name: 检查分配的服务器性能
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT        
          
      - name: 初始化编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          #sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo -E apt-get -qq update --fix-missing
          sudo -E apt-get -qq full-upgrade
          sudo -E apt-get -qq install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev dos2unix
          sudo -E apt-get -qq install time gn
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "status=success" >> ${GITHUB_OUTPUT}
          df -Th        

      - name: 初始化变量
        run: |
          export OWRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export OWRT_SOURCE=$(echo $OWRT_URL | cut -d '/' -f 5-)
          #export OWRT_TYPE="cortex-a53"

          echo "OWRT_SOURCE=$OWRT_SOURCE" >> $GITHUB_ENV
          echo "OWRT_TARGET=$OWRT_TARGET" >> $GITHUB_ENV
          echo "OWRT_DATE=$OWRT_DATE" >> $GITHUB_ENV
          echo "OWRT_TYPE=$OWRT_TYPE" >> $GITHUB_ENV
          echo "OWRT_PW=$OWRT_PW" >> $GITHUB_ENV
          echo "OWRT_IP=$OWRT_IP" >> $GITHUB_ENV
          echo "OWRT_LINUX=$OWRT_LINUX" >> $GITHUB_ENV
          echo "OWRT_FILES=$OWRT_FILES" >> $GITHUB_ENV
          echo "DIY_P1_SH=$DIY_P1_SH" >> $GITHUB_ENV
          echo "DIY_P2_SH=$DIY_P2_SH" >> $GITHUB_ENV
          echo "DIY_P3_SH=$DIY_P3_SH" >> $GITHUB_ENV

      - name: 检查脚本
        run: |
          cd ./Scripts
          
          dos2unix ./*.sh
          chmod +x ./*.sh

      - name: 克隆源码库
        working-directory: /workdir
        run: |
          # Set up compilation source code
          if [[ "${{ inputs.OWRT_URL }}" == *"openwrt/openwrt"* ]]; then
              REPO_URL="https://github.com/openwrt/openwrt"
              REPO_BRANCH="main"
              TAGS_NAME="official"
          elif [[ "${{ inputs.OWRT_URL }}" == *"coolsnowwolf/lede"* ]]; then
              REPO_URL="https://github.com/coolsnowwolf/lede"
              REPO_BRANCH="master"
              TAGS_NAME="lede"
          elif [[ "${{ inputs.OWRT_URL }}" == *"immortalwrt/immortalwrt"* ]]; then
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
              REPO_BRANCH="master"
              TAGS_NAME="immortalwrt"
          else
              REPO_URL="${{ inputs.OWRT_URL }}"
              REPO_BRANCH="${{ inputs.OWRT_BRANCH }}"
              TAGS_NAME="${{ inputs.OWRT_TARGET }}"
          fi
         
          if [[ $OWRT_LINUX == *"5.4"* ]] ; then
            REPO_BRANCH="${{ inputs.OWRT_BRANCH }}"
          fi
          
          df -hT $PWD
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt 
          
          if [[ "${{ inputs.OWRT_CFG }}" == *"ax5_wifi.config"* ]]; then
            echo "DEVICE_NAME=redmi_ax5" >> $GITHUB_ENV
          else
            [ -e $GITHUB_WORKSPACE/Config/$OWRT_CFG ] && echo "DEVICE_NAME=$(grep '^CONFIG_TARGET_.*_.*_DEVICE_.*=y' $GITHUB_WORKSPACE/Config/$OWRT_CFG | sed -r 's/.*DEVICE_(.*)=y/\1/')" >> $GITHUB_ENV            
          fi
          
      - name: 加载自定义订阅源
        run: |
          cd openwrt
          if [[ "${{ inputs.OWRT_CFG }}" == *"ax5_wifi.config"* ]]; then
            sudo mv $GITHUB_WORKSPACE/ax5/feeds.conf.default ./feeds.conf.default
            ${GITHUB_WORKSPACE}/Scripts/quick.sh
            #echo 'src-git kiddin9 https://github.com/kiddin9/openwrt-packages' >> feeds.conf.default
          else
            ${GITHUB_WORKSPACE}/Scripts/${DIY_P1_SH}
          fi
          
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 给openwrt库打补丁
        run: |
          if [[ "${{ inputs.OWRT_URL }}" == *"openwrt"* ]]; then
            cd openwrt 
            #mv $GITHUB_WORKSPACE/patch/0001-ipq807x-add-stock-layout-variant-for-redmi-ax6.patch 0001-ipq807x-add-stock-layout-variant-for-redmi-ax6.patch
            #git apply 0001-ipq807x-add-stock-layout-variant-for-redmi-ax6.patch
            
            sudo chmod +x $GITHUB_WORKSPACE/patch/*.sh
            sudo chmod -Rf 755 $GITHUB_WORKSPACE/patch/*
            sudo mv $GITHUB_WORKSPACE/patch/01_leds target/linux/qualcommax/ipq807x/base-files/etc/board.d/01_leds
            sudo mv $GITHUB_WORKSPACE/patch/02_network target/linux/qualcommax/ipq807x/base-files/etc/board.d/02_network
            sudo mv $GITHUB_WORKSPACE/patch/11-ath10k-caldata target/linux/qualcommax/ipq807x/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
            sudo mv $GITHUB_WORKSPACE/patch/11-ath11k-caldata target/linux/qualcommax/ipq807x/base-files/etc/hotplug.d/firmware/11-ath11k-caldata
            sudo mv $GITHUB_WORKSPACE/patch/bootcount target/linux/qualcommax/ipq807x/base-files/etc/init.d/bootcount
            sudo mv $GITHUB_WORKSPACE/patch/platform.sh target/linux/qualcommax/ipq807x/base-files/lib/upgrade/platform.sh
            sudo mv $GITHUB_WORKSPACE/patch/ipq807x.mk target/linux/qualcommax/image/ipq807x.mk 
            sudo mv $GITHUB_WORKSPACE/patch/ipq8071-ax6-stock.dts target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8071-ax6-stock.dts
            sudo mv $GITHUB_WORKSPACE/patch/ipq8071-ax3600-stock.dts target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8071-ax3600-stock.dts
          else
            echo "不是openwrt库不用打补丁！"
          fi           

      - name: 启动缓存[第二次起生效]
        uses: rmoyulong/cachewrtbuild@main
        with:
          ccache: 'true'
          prefix: ${{ github.workspace }}/openwrt
          mixkey: ${{ env.OWRT_URL }}/tree/${{ env.OWRT_BRANCH }}?device=${{ env.OWRT_CFG }}

      - name: 更新订阅源
        run: |
          cd openwrt
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
  
      - name: 更新ipq6018补丁   
        run: |
          if [[ "${{ inputs.OWRT_CFG }}" == *"ax5_wifi.config"* ]]; then
            cd openwrt        
            git config --global user.name "OpenWrt Builder"
            git config --global user.email "buster-openwrt@ovvo.uk"
            cd feeds/luci
            wget https://raw.githubusercontent.com/openwrt-ipq60xx/patches/main/feeds/luci/0001-show-soc-status-on-luci.patch
            git am 0001-show-soc-status-on-luci.patch
          else
            echo "不是ipq6018自定义库不用打补丁！"
          fi

      - name: 自定义脚本
        run: |
          cd openwrt
          if [[ "${{ inputs.OWRT_URL }}" == *"openwrt"* ]]; then
            rm -rf feeds/packages/lang/golang
            git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang
          fi
         
          cp -rf $GITHUB_WORKSPACE/ax6/banner package/base-files/files/etc/banner
          
          if [[ $DIY_P1_SH == *"Plugins_k2_L1.sh"*  ]] ; then
            $GITHUB_WORKSPACE/Scripts/Settings.sh
          elif [[ $DIY_P1_SH == *"Plugins_k3.sh"*  ]] ; then
            $GITHUB_WORKSPACE/Scripts/Settings.sh
            
            echo '移除主页跑分信息显示'
            sed -i 's/ <%=luci.sys.exec("cat \/etc\/bench.log") or ""%>//g' package/lean/autocore/files/arm/index.htm
            echo '=========Remove benchmark display in index OK!========='            
           
            echo '修改upnp绑定文件位置'
            sed -i 's/\/var\/upnp.leases/\/tmp\/upnp.leases/g' feeds/packages/net/miniupnpd/files/upnpd.config
            cat feeds/packages/net/miniupnpd/files/upnpd.config |grep upnp_lease_file
            echo '=========Alert upnp binding file directory!========='
            
            echo '添加主页的CPU温度显示'
            sed -i "/<tr><td width=\"33%\"><%:Load Average%>/a \ \t\t<tr><td width=\"33%\"><%:CPU Temperature%></td><td><%=luci.sys.exec(\"sed 's/../&./g' /sys/class/thermal/thermal_zone0/temp|cut -c1-4\")%></td></tr>" feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
            cat feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm |grep Temperature
            echo "Add CPU Temperature in Admin Index OK====================="
           
          elif [[ $DIY_P1_SH == *"quick.sh"*  ]] ; then
            #rm -rf feeds/small/luci-app-ssr-plus
            #rm -rf feeds/small/shadowsocksr-libev
            rm -rf package/feeds/packages/shadowsocks-libev            
            
            $GITHUB_WORKSPACE/Scripts/Settings.sh
            #删除冲突的插件 
            #rm -rf feeds/kiddin9/{base-files,dnsmasq,fk3irewall*,fullconenat,libnftnl,nftables,ppp,opkg,ucl,upx,vsftpd-alt,miniupnpd-iptables,wireless-regdb}
          else
            $GITHUB_WORKSPACE/Scripts/Settings.sh
            #删除冲突的插件 
            rm -rf feeds/kiddin9/{base-files,dnsmasq,firewall*,fullconenat,libnftnl,nftables,ppp,opkg,ucl,upx,vsftpd-alt,miniupnpd-iptables,wireless-regdb}
          fi
          
          if [[ $OWRT_LINUX == *"6.1.x"*  ]] ; then
            cd ./package          
            $GITHUB_WORKSPACE/Scripts/custom.sh
          fi

      - name: 自定义设置
        run: |
          [ -e $GITHUB_WORKSPACE/$OWRT_FILES ] && mv $GITHUB_WORKSPACE/$OWRT_FILES openwrt/files
          cd openwrt

          rm -rf ./tmp* ./.config*
          #rm -rf $(find ./ -type f -iname "*.config*") 
          #make dirclean
          [ -e $GITHUB_WORKSPACE/Config/$OWRT_CFG ] && mv $GITHUB_WORKSPACE/Config/$OWRT_CFG .config
          
          #openwrt库[不支持unblockneteasemusic unblockmusic]
          if [[ "${{ inputs.OWRT_URL }}" == *"openwrt"* ]]; then
            echo -e 'CONFIG_PACKAGE_luci-app-unblockmusic=n\n' >> .config
            echo -e 'CONFIG_PACKAGE_luci-app-unblockneteasemusic=n\n' >> .config
          fi
          
          #nftable设置
          if [[ $OWRT_LINUX == *"6.1"*  ]] ; then
            [ -e $GITHUB_WORKSPACE/patch/files ] && mv $GITHUB_WORKSPACE/patch/files ./files
          fi
          
          make defconfig

      - name: 下载编译依赖
        working-directory: ./openwrt
        run: |
          make download -j$(nproc)
          #make download -j8
          #make -j16 download
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: 编译固件
        working-directory: ./openwrt
        run: |     
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV  

      - name: 整理固件
        run: |
          cd openwrt && mkdir ./upload

          rm -rf $(find ./bin/targets/ -iregex ".*\(json\|manifest\|buildinfo\|sha256sums\|packages\)$")
          cp -rf $(find ./bin/targets/ -type f -iname "*.*") ./upload/
          cp -rf ./.config ./upload/Config_"$OWRT_TARGET"_"$OWRT_SOURCE"_"$OWRT_DATE".txt

          cd ./upload

          $GITHUB_WORKSPACE/Scripts/Renames.sh

      - name: 生成固件标签
        uses: rmoyulong/action-gh-release@master
        with:
          tag_name: ${{env.OWRT_TARGET}}_${{env.OWRT_SOURCE}}_${{env.OWRT_DATE}}
          files: openwrt/upload/*.*
          body: |
            个人使用的路由器固件！
            刷机有风险！刷前需谨慎！

            源码：${{env.OWRT_SOURCE}}
            平台：${{env.OWRT_TARGET}}
            设备：${{env.OWRT_TYPE}}
            密码：${{env.OWRT_PW}}
            地址：${{env.OWRT_IP}}
            内核：${{env.OWRT_LINUX}}

      - name: 清理Releases
        uses: rmoyulong/delete-older-releases@master
        with:
          keep_latest: 10
          delete_tags: true

      - name: 清理Workflows
        uses: rmoyulong/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
