#CI项目名
name: lede-youku_L1

on:
  #自动编译：每天早上4点
  #schedule:
    #- cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/OWRT-CORE-Lite.yml
    with:
      #编译平台，X64包含X86
      OWRT_TARGET: youku_L1
      #默认主题
      OWRT_THEME: argon
      #默认主机名
      OWRT_NAME: youku_L1
      #默认密码，仅作展示，更改无效
      OWRT_PW: password
      #默认地址
      OWRT_IP: 192.168.31.1
      #默认源码
      OWRT_URL: https://github.com/coolsnowwolf/lede
      #源码版本
      OWRT_BRANCH: main
      #自定义config
      OWRT_CFG: youku_L1.config
      #设备类型
      OWRT_TYPE: 优酷路由宝L1
      OWRT_LINUX: 5.10.x
      OWRT_FILES: youku/files
      DIY_P1_SH: Plugins.sh
      DIY_P2_SH: Settings.sh
      DIY_P3_SH: custom.sh